name: "AdventOfCode CI"

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'
      - 'Package.swift'
      - 'Source/**'
      - 'Tests/**'
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'Package.swift'
      - 'Source/**'
      - 'Tests/**'

jobs:
  macOS:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Resolve
      run: cd 2022 && swift package resolve
    - name: Build
      run: cd 2022 && swift build
    - name: Run tests
      run: cd 2022 && swift test 2>&1 | xcpretty
  linux:
    runs-on: ubuntu-latest
    container: swift:5.7
    steps:
      - uses: actions/checkout@v3
      - name: Resolve
        run: cd 2022 && swift package resolve
      - name: Build
        run: cd 2022 && swift build
      - name: Run tests
        run: cd 2022 && swift test 2>&1